spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://182.254.148.73:3306/sell?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: xiaolu123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  context-path: /sell
